### PR TITLE
fix: Update NesTooltip to use OverlayPortal

### LINKED ISSUE #159: fix: NesTooltip displays below other widgets
**Description**

NesTooltip displays below other widgets.

**Steps To Reproduce**

1. Place a NesTooltip with child (I used NesButton)
2. Place another Widget after the NesTooltip in an area where it will overlap the displayed tooltip. (I used another NesButton)
3. Activate the NesTooltip.
4. See Screenshot.

**Expected Behavior**

The NesTooltip should not be covered by other widgets.

**Screenshots**

Image

**Additional Context**

Suggestion: Use [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html)
A widget that renders its overlay child on an Overlay.

### PR DESCRIPTION
**Pull request by moldypenguins**
fixes #159 

Top  
image
image
image

Bottom  
image
image
image

## Status

**READY** (needs testing on web and mobile, also with other children besides NesButton)

* Has been tested as Windows application and with a NesButton as the child

## Description

Updated NesTooltip to use [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html).

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

### CODE REVIEW

**Comment by moldypenguins** [comment]
fixes #159

File: lib/src/widgets/nes_tooltip.dart [hunk 1]
```diff
@@ -53,8 +52,66 @@ class NesTooltip extends StatefulWidget {
   State<NesTooltip> createState() => _NesTooltipState();
 }
 
-class _NesTooltipState extends State<NesTooltip> {
-  var _show = false;
+class _NesTooltipState extends State<NesTooltip>
+    with SingleTickerProviderStateMixin<NesTooltip> {
+  // Controller for managing the overlay portal.
+  final OverlayPortalController _controller = OverlayPortalController();
```
Comment (erickzanardo) [inline lib/src/widgets/nes_tooltip.dart:58]:
```suggestion
  final _controller = OverlayPortalController();
```

**Review by erickzanardo — APPROVED** [review]
